export default [
  "Grocery",
  "Electronics",
  "Cloths & Footwear",
  "Home & Kitchen",
  "Books",
  "Beauty & Personal Care",
  "Sports & Outdoors",
  "Toys & Games",
  "Automotive",
  "Health & Wellness",
  "Office Supplies",
  "Baby Products",
  "Pet Supplies",
  "Furniture",
  "Jewelry",
  "Shoes",
  "Accessories",
  "Appliances",
  "Musical Instruments",
  "Garden & Outdoor",
];
